config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :organizations
  resources :guardianships

  root to: 'guardianships#index'

  get 'guardianships/:id/end' => 'guardianships#end', as: :end_guardianship

end

app/models/guardianship.rb
class Guardianship < ActiveRecord::Base
  belongs_to :user

end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :guardianships

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guardianships_controller.rb
class GuardianshipsController < ApplicationController
  before_action :set_guardianship, only: [:end, :show, :edit, :update, :destroy]

  # GET /guardianships
  # GET /guardianships.json
  def index
    @guardianships = Guardianship.where(endtime: nil)
    if user_signed_in?
      @user_guardianship = Guardianship.where(user_id: current_user.id).where(endtime: nil).take
    end
  end

  # GET /guardianships/1
  # GET /guardianships/1.json
  def show

  end

  # GET /guardianships/new
  def new
    if user_signed_in?
      @guardianship = Guardianship.new

    else
      redirect_to new_user_session_path
    end
  end

  # GET /guardianships/1/edit
  def edit
  end

  def end
    if current_user.id == @guardianship.user_id
      @guardianship.endtime = DateTime.now
      respond_to do |format|
        if @guardianship.save
          format.html { redirect_to @guardianship, notice: 'Hienosti poistuttu.' }
          format.json { render :show, status: :created, location: @guardianship }
        else
          format.html { render :new }
          format.json { render json: @guardianship.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = "Jäbä koittaa lopettaa muiden vastuun."
    end
  end

  # POST /guardianships
  # POST /guardianships.json
  def create
    @guardianship = Guardianship.new(guardianship_params)
    @guardianship.user_id = current_user.id

    respond_to do |format|
      if @guardianship.save
        format.html { redirect_to root_path, notice: 'Guardianship was successfully created.' }
        format.json { render :show, status: :created, location: @guardianship }
      else
        format.html { render root }
        format.json { render json: @guardianship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guardianships/1
  # PATCH/PUT /guardianships/1.json
  def update
    respond_to do |format|
      if @guardianship.update(guardianship_params)
        format.html { redirect_to @guardianship, notice: 'Guardianship was successfully updated.' }
        format.json { render :show, status: :ok, location: @guardianship }
      else
        format.html { render :edit }
        format.json { render json: @guardianship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guardianships/1
  # DELETE /guardianships/1.json
  def destroy
    @guardianship.destroy
    respond_to do |format|
      format.html { redirect_to guardianships_url, notice: 'Guardianship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guardianship
      @guardianship = Guardianship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guardianship_params
      params.require(:guardianship).permit(:endtime)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :ban)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guardianships_helper.rb
module GuardianshipsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guardianships/_form.html.erb
<%= form_for(@guardianship) do |f| %>
  <% if @guardianship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guardianship.errors.count, "error") %> prohibited this guardianship from being saved:</h2>

      <ul>
      <% @guardianship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Viesti' %><br>
    <%= f.text_area :description_text, cols: "30", rows: "10"%>
  </div>
  <div class="actions">
    <%= f.submit "Liity vastuuseen"%>-
  </div>
<% end %>

app/views/guardianships/edit.html.erb
<h1>Editing Guardianship</h1>

<%= render 'form' %>

<%= link_to 'Show', @guardianship %> |
<%= link_to 'Back', guardianships_path %>

app/views/guardianships/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Tämänhetkiset vastuut:</h1>

<% if @guardianships.empty? %>
    Kukaan ei ole vastuussa!
<% else %>
    <% @guardianships.each do |g| %>
        <p><%= g.user.name %> on vastuussa:
          <% if not g.description_text.nil? %>
              <%= g.description_text %><br>
          <% end %>
          vastuu alkoi
          <%= g.created_at.strftime("%H:%M") %></p>
    <% end %>
<% end %>
<br>
<% if user_signed_in? && @user_guardianship == nil %>
    <%= link_to 'Liity vastuuseen', new_guardianship_path %>
<% end %>
<% if @user_guardianship %>

    <%= text_area(:guardianship, :leave_text) %><br>
    <%= link_to 'Poistu vastuusta', end_guardianship_path(@user_guardianship.id) %>

<% end %>

app/views/guardianships/new.html.erb
<h1>Liity vastuuseen</h1>

<%= render 'form' %>

<%= link_to 'Takaisin', guardianships_path %>

app/views/guardianships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endtime:</strong>
  <%= @guardianship.endtime %>
</p>

<%= link_to 'Edit', edit_guardianship_path(@guardianship) %> |
<%= link_to 'Back', guardianships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bmur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navibar">
  <%= link_to 'Tämän hetken vastuulliset', guardianships_path %>
  <% if user_signed_in? %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Log in', new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ban %><br>
    <%= f.check_box :ban %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ban</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.ban %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Ban:</strong>
  <%= @organization.ban %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p>Täällä ei vissiin tarvii olla mitään?</p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>